### PR TITLE
Feature: Line Mode (#40)

### LINKED ISSUE #38: Jump to Bookmark commands are producing errors
vscode 1.59.0

Error message:
Running the contributed command: 'inlineBookmarks.jumpToNext' failed.

Hi!
Running in the debugger, it looks like there are a few places where you're accessing the activeEditor selections array via private variable instead of using the getter.  Recent versions of vscode have apparently removed access to the private vars, causing the error.  Simply removing the underscore seems to resolve it.

I'll send a pull request for you shortly.
Thanks!!

### LINKED ISSUE #40: Feature:  Jump to Next/Prev Bookmark based on cursor position
Your extensions has a really great combination of bookmarking and todo lists into a simple view.  In particular, this extension is the only one I've found that also combines both follow-mode and the ability to Jump around the document based on bookmarks.  Thanks!!

Here's my proposal for a new feature (and a pull request):

- By default the Jump to Next/Prev is an extension of the follow-mode, which makes a lot of sense.
- I **do not** want to change the follow behavior - it's great as-is
- The use-case comes from Notepad++ and how it handles Bookmarks
- It's close to Chapter Mode, but just a little bit different.
- The idea is to base the jump on the current line position instead of the current followed/selected bookmark
-- I've called it "Line Mode" in my pull request - it's the best I could come up with!!  :)

It's a subtle change, but a crucial one when paired with using Keyboard shortcuts for Next/Prev.  Wherever the cursor is
- Next should always jump to the closest Bookmark below the cursor
- Prev should always jump to the closest Bookmark above the cursor

Last, I considered coding it as a 3rd follow-mode, but I think it's not really a follow mode.  I've added this feature as a new boolean optional toggle.  It works with both "nearest" and "chapter" modes, and also work when follow mode is disabled.

### PR DESCRIPTION
**Pull request by rkodey**
Resolves #40 
Fixes #38 (included)

### CODE REVIEW

**Comment by tintinweb** [comment]
awesome 🙌 this is great @rkodey! I am thinking about turning the setting from `bool` to `enum` just in case there'll be another line mode to avoid  :) I'll try to get this tested later today.

**Comment by rkodey** [comment]
Cool - glad I could contribute an idea!

The next thing I was considering...  an option to wrap-around.  So, jumping to "Next" from the last bookmark would jump to the first bookmark.

Perhaps that's a good reason to use your `enum` instead of `bool`!

**Comment by tintinweb** [comment]
> The next thing I was considering... an option to wrap-around. So, jumping to "Next" from the last bookmark would jump to the first bookmark.
> 
> Perhaps that's a good reason to use your `enum` instead of `bool`!

Happy to receive a PR on this. Would probably make sense to make this the default behavior 🤔

**Comment by rkodey** [comment]
Ok - I'll rebase on your enum update and fiddle with the wrap-around feature a bit.  Notepad++ wraps by default, so I agree that might be the best default here as well.  Perhaps an option to turn off wrapping as part of your enum...  but "keep it simple" might suggest making wrapping the default, then wait for user feedback.

Probably later this week...

**Pull request merged**
